### Terraform template
.terraform
*.tfstate
*.tfstate.*
crash.log
*.tfvars
override.tf
override.tf.json
*_override.tf
*_override.tf.json
.terraformrc
terraform.rc
*.plan

### K8s and EKS
# Ignore the kubectl configuration, this is very sensitive information.
.kube/*
!/.kube/config

# Ignore Helm Values
*/values.prod.yaml

# Ignore SSH keys
*.pem

# Ignore kubeconfig files generated by eksctl command
kubeconfig_*